language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get -y install tree
script:
    - export CC="$CC" TEST_PREFIX="`pwd`/test_prefix" LOGDIR="`pwd`/testprefix/var/log/marunage"
    - make CC="$CC" PREFIX="${TEST_PREFIX}" LOGDIR="$LOGDIR"
    - make CC="$CC" PREFIX="${TEST_PREFIX}" LOGDIR="$LOGDIR" install
    - tree ${TEST_PREFIX}
    - ${TEST_PREFIX}/bin/marunage --version
    - ${TEST_PREFIX}/bin/marunage --help
    - make clean
    - rm -rf ${TEST_PREFIX}
    - unset TEST_PREFIX
